api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt import views as jwt_views
from drf_yasg.views import get_schema_view
from drf_yasg import openapi



schema_view = get_schema_view(
   openapi.Info(
      title="ArticlesAPI",
      default_version='v1',
      description="Test description",
      
   ),
)



urlpatterns = [path('noticias/', views.NoticiasListView.as_view(), name='list_noticias'),               
               path('noticias/<pk>/', views.NoticiasDetailView.as_view(), name='retrieve_article'),
               # path('<str:fonte>/noticias/', views.NoticiaFonteView.as_view()),               
               path('token/', jwt_views.TokenObtainPairView.as_view(),
                    name='token_obtain_pair'),
               path('token/refresh', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
               path('schema/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),]

monitoramento/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noticias/', include('noticias.urls', namespace='noticias')),
    path('api/', include('api.urls')),
    path('api/user/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

noticias/urls.py
from django.urls import path
from . import views


app_name = 'noticias'

urlpatterns = [
    path("", views.lista_noticias, name="lista_noticias"),
    path("procurar/", views.procurar_noticias, name="procurar_noticias"),
    path("<slug:slug>/", views.detalha_noticia, name="detalha_noticia"),
   
    path("<str:fonte>", views.noticias_por_veiculo, name="noticias_por_veiculo"),
    path("compartilha_noticia/<slug:slug>/", views.compartilha_noticia, name="compartilha_noticia")
]

noticias/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class Noticia(models.Model):
    titulo = models.CharField(max_length=200, unique=True)
    data_noticia = models.DateField()
    fonte = models.CharField(max_length=50)
    conteudo = models.TextField()
    url = models.URLField()
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse("noticias:detalha_noticia", kwargs={"slug": self.slug})

    class Meta:
        ordering = ['-data_noticia']

noticias/forms.py
from django import forms
from django.forms.widgets import Textarea


class ShareNoticiaForm(forms.Form):
    nome = forms.CharField(max_length=30)
    email = forms.EmailField()
    send_to = forms.EmailField()
    comentarios = forms.CharField(required=False, widget=forms.Textarea)

class SearchForm(forms.Form):
    query=forms.CharField()

noticias/views.py
from django.shortcuts import render, get_object_or_404
from .models import Noticia
from django.core.paginator import Paginator
from .forms import ShareNoticiaForm,SearchForm
from django.core.mail import send_mail
from django.contrib.postgres.search import SearchVector
# Create your views here.


def lista_noticias(request):
    noticias = Noticia.objects.all()
    paginator = Paginator(noticias, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'noticias/lista_noticias.html', {'page_obj': page_obj})


def detalha_noticia(request, slug):
    noticia = get_object_or_404(Noticia, slug=slug)

    return render(request, 'noticias/detalha_noticia.html', {'noticia': noticia})


def procurar_noticias(request):
    form=SearchForm()
    query=None
    results=[]
    if 'query' in request.GET:
        form=SearchForm(request.GET)
        if form.is_valid():
            query=form.cleaned_data['query']
            results=Noticia.objects.annotate(search=SearchVector('titulo','conteudo'),).filter(search=query)
    return render(request,'noticias/procurar.html',{'form':form,'query':query,'results':results})


def noticias_por_veiculo(request, fonte):
    noticias_veiculo = Noticia.objects.filter(fonte__contains=fonte)
    paginator = Paginator(noticias_veiculo, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'noticias/noticias_por_veiculo.html', {'page_obj': page_obj})


def compartilha_noticia(request, slug):
    noticia = get_object_or_404(Noticia, slug=slug)
    sent = False
    if request.method == 'POST':
        form = ShareNoticiaForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(noticia.get_absolute_url())
            subject = f"{cd['nome']} recomenda que você leia" \
                f"{noticia.titulo}"
            message = f" Leia {noticia.titulo} em {post_url} \n\n" \
                f"{cd['nome']}\'s comments: {cd['comentarios']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['send_to']])

            sent = True

    else:
        form = ShareNoticiaForm()
    return render(request, "noticias/compartilha_noticia.html", {'form': form,
                                                                 'noticia': noticia,
                                                                 'sent': sent})

noticias/templates/noticias/compartilha_noticia.html
{% extends 'noticias/index.html'%}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    {% if sent %}
    <h1> E-mail enviado com sucesso!</h1>
    <p> {{ noticia.titulo}} foi enviada com sucesso para {{ form.cleaned_data.send_to}}</p>
    {% else %}
        <h1> Compartilhe por email a noticia "{{ noticia.titulo}}".</h1>
        <div class="form-group">
            <form method="post">
                {{ form|crispy }}
                {% csrf_token %}
                <input type="submit" value="Enviar e-mail">
            </form>
        </div>
    {% endif %}
{% endblock %}    

noticias/templates/noticias/detalha_noticia.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>News hub</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'noticias/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'noticias/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'noticias/css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'noticias:lista_noticias' %}">Home</a>
          </li>
          
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead mb-2" style="background-image: url('/media/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-10 col-md-10 mx-auto">
          <div class="post-heading">
            {% if noticia %}
            <h1> {{ noticia.titulo }}</h1>
            <span class="meta">Publicado por {{ noticia.fonte }}
              em {{ noticia.data_noticia}}</span>
              <a class="text-white" href="{% url 'noticias:compartilha_noticia' noticia.slug %}">Compartilhe a notícia</a>
              {% endif %}  
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-10 col-md-10 mx-auto">
          {% if noticia %}
          <p align="justify">{{ noticia.conteudo}}</p>
          {% endif %}
          
        </div>
      </div>
    </div>
  </article>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'noticias/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'noticias/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'noticias/js/clean-blog.min.js' %}"></script>

</body>

</html>

noticias/templates/noticias/detalha_noticias.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SIMIP</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'noticias/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'noticias/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'noticias/css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'noticias:lista_noticias' %}">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'noticias:lista_noticias' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('/media/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            {% if noticias %}
            <h1> {{ noticias.titulo }}</h1>
            <span class="meta">Publicado por
              <a href="#">{{ noticias.fonte }}</a>
              em {{ noticias.data_noticia}}</span>
            {% endif %}  
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          {% if noticias %}
          <p align="justify">{{ noticias.conteudo}}</p>
          {% endif %}
          
        </div>
      </div>
    </div>
  </article>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'noticias/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'noticias/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'noticias/js/clean-blog.min.js' %}"></script>

</body>

</html>

noticias/templates/noticias/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>News Hub</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'noticias/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'noticias/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'noticias/css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'noticias:lista_noticias' %}">Home</a>
          </li>
          
        </ul>
      </div>
    </div>
  </nav>
  
   
    <!-- Page Header -->
  <header class="masthead mb-2" style="background-image: url('../media/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>News Hub</h1>
            <span class="subheading">Acompanhamento de notícias </span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>     
      
    
  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'noticias/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'noticias/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'noticias/js/clean-blog.min.js' %}"></script>

</body>

</html>

noticias/templates/noticias/lista_noticias.html
{% extends 'noticias/index.html' %}

{% block content %}
<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <div class="post-preview">
        {% if page_obj %}
        {% for noticia in page_obj %}
        <a href="{{ noticia.get_absolute_url }}">
          <h2 class="post-title"> {{ noticia.titulo }}</h2>
        </a>
        <p class="post-meta">Publicado por {{ noticia.fonte }} em {{ noticia.data_noticia}}</p>
        <p>{{noticia.conteudo|truncatewords:30|linebreaks}}</p>
        <hr>
        {% endfor %}
        {% else %}
        {% endif %}
      </div>
    </div>


    {% include 'noticias/partials/sidebar.html' %}




  </div>
  <!-- /.row -->
  {% include 'noticias/partials/pagination.html' %}
</div>
{% endblock %}

noticias/templates/noticias/noticias_por_veiculo.html
{% extends 'noticias/lista_noticias.html' %}

noticias/templates/noticias/procurar.html
{% extends 'noticias/index.html' %}
{% load static %}

{% block title %} Pesquisa noticias {% endblock %}
{% block content %}

 
   
  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">
          {% if query %}
            <h1> Noticias contendo a palavra "{{query}}"</h1>
            <h3>{% with results.count as total_results %}
              {{total_results}} Encontrado{{total_results|pluralize}}
              {% endwith %}
            </h3>
            <hr>
            {% for noticia in results %}
            <h4><a href="{{ noticia.get_absolute_url}}">{{noticia.titulo}}</a></h4>
            <p class="post-meta">Publicado por
              <a href="#">{{ noticia.fonte }}</a>
              em {{ noticia.data_noticia}}</p>
            
            <hr>
            {% empty %}
              <p>Não há resultaods para a pesquisa.</p>
            {% endfor %}
            
            
           
          {% else %}
            <div class="col-lg-8 col-md-10 mx-auto">
                <p> Noticia não encontrada</p>
            </div>
          {% endif %}
          </div>
          
        </div>
        <div class="sidebar">
          <h5 class="card-header">Procurar notícia</h5>
          <div class="card-body">
            <div class="input-group">
              <form action="{% url 'noticias:procurar_noticias' %}">
                <input type="text" class="form-control" name="query" placeholder="Procurar por...">
                <button class="btn btn-secondary" type="submit">Ir!</button>
              </form>
            </div>
          </div>  
        </div>
      </div>
    </div>
  </div> 
  
{% endblock%}