api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt import views as jwt_views
from drf_yasg.views import get_schema_view
from drf_yasg import openapi



schema_view = get_schema_view(
   openapi.Info(
      title="ArticlesAPI",
      default_version='v1',
      description="Test description",
      
   ),
)



urlpatterns = [path('noticias/', views.NoticiasListView.as_view(), name='list_noticias'),               
               path('noticias/<pk>/', views.NoticiasDetailView.as_view(), name='retrieve_article'),
               # path('<str:fonte>/noticias/', views.NoticiaFonteView.as_view()),               
               path('token/', jwt_views.TokenObtainPairView.as_view(),
                    name='token_obtain_pair'),
               path('token/refresh', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
               path('schema/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),]

monitoramento/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noticias/', include('noticias.urls', namespace='noticias')),
    path('api/', include('api.urls')),
    path('api/user/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

noticias/urls.py
from django.urls import path
from . import views


app_name = 'noticias'

urlpatterns = [
    path("", views.lista_noticias, name="lista_noticias"),
    path("procurar/", views.procurar_noticias, name="procurar_noticias"),
    path("<slug:slug>/", views.detalha_noticia, name="detalha_noticia"),
   
    path("<str:fonte>", views.noticias_por_veiculo, name="noticias_por_veiculo"),
    path("compartilha_noticia/<slug:slug>/", views.compartilha_noticia, name="compartilha_noticia")
]

noticias/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class Noticia(models.Model):
    titulo = models.CharField(max_length=200, unique=True)
    data_noticia = models.DateField()
    fonte = models.CharField(max_length=50)
    conteudo = models.TextField()
    url = models.URLField()
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse("noticias:detalha_noticia", kwargs={"slug": self.slug})

    class Meta:
        ordering = ['-data_noticia']

noticias/forms.py
from django import forms
from django.forms.widgets import Textarea


class ShareNoticiaForm(forms.Form):
    nome = forms.CharField(max_length=30)
    email = forms.EmailField()
    send_to = forms.EmailField()
    comentarios = forms.CharField(required=False, widget=forms.Textarea)

class SearchForm(forms.Form):
    query=forms.CharField()

noticias/views.py
from django.shortcuts import render, get_object_or_404
from .models import Noticia
from django.core.paginator import Paginator
from .forms import ShareNoticiaForm,SearchForm
from django.core.mail import send_mail
from django.contrib.postgres.search import SearchVector
# Create your views here.


def lista_noticias(request):
    noticias = Noticia.objects.all()
    paginator = Paginator(noticias, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'noticias/lista_noticias.html', {'page_obj': page_obj})


def detalha_noticia(request, slug):
    noticia = get_object_or_404(Noticia, slug=slug)

    return render(request, 'noticias/detalha_noticia.html', {'noticia': noticia})


def procurar_noticias(request):
    form=SearchForm()
    query=None
    results=[]
    if 'query' in request.GET:
        form=SearchForm(request.GET)
        if form.is_valid():
            query=form.cleaned_data['query']
            results=Noticia.objects.annotate(search=SearchVector('titulo','conteudo'),).filter(search=query)
    return render(request,'noticias/procurar.html',{'form':form,'query':query,'results':results})


def noticias_por_veiculo(request, fonte):
    noticias_veiculo = Noticia.objects.filter(fonte__contains=fonte)
    paginator = Paginator(noticias_veiculo, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'noticias/noticias_por_veiculo.html', {'page_obj': page_obj})


def compartilha_noticia(request, slug):
    noticia = get_object_or_404(Noticia, slug=slug)
    sent = False
    if request.method == 'POST':
        form = ShareNoticiaForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(noticia.get_absolute_url())
            subject = f"{cd['nome']} recomenda que você leia" \
                f"{noticia.titulo}"
            message = f" Leia {noticia.titulo} em {post_url} \n\n" \
                f"{cd['nome']}\'s comments: {cd['comentarios']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['send_to']])

            sent = True

    else:
        form = ShareNoticiaForm()
    return render(request, "noticias/compartilha_noticia.html", {'form': form,
                                                                 'noticia': noticia,
                                                                 'sent': sent})

noticias/templates/noticias/partials/pagination.html
<div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
        <a href="?page=1">Primeira</a>
        <a href="?page={{page_obj.previous_page_number}}"> Página anterior </a>
      {% endif %}  
      <span class="current">
        Página {{ page_obj.number}} de {{ page_obj.paginator.num_pages}}.
      </span>            
      {% if page_obj.has_next %} 
        <a href="?page={{page_obj.next_page_number}}"> Próxima página</a>
        <a href="?page={{page_obj.paginator.num_pages}}">Última</a> 
      {% endif %}
    </span>
    
  </div>
</div>

noticias/templates/noticias/partials/sidebar.html
<!-- Sidebar Widgets Column -->
<div class="col-md-4">
  <div class="card my-4">
    <h5 class="card-header">Procurar</h5>
    <div class="card-body">
      <form action="{% url 'noticias:procurar_noticias' %}">
        <div class="input-group">
          <input type="text" class="form-control" name="query" placeholder="Procurar por...">
          <span class="input-group-append">
            <button class="btn btn-primary p-1" type="submit">Buscar</button>
          </span>
        </div>
      </form>
    </div>
  </div>
  <!-- Categories Widget -->
  <div class="card my-4">
    <h5 class="card-header">Categorias</h5>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-6">
          <ul class="list-unstyled mb-0">

            <li>
              <a href="{% url 'noticias:noticias_por_veiculo' 'Ebc' %}">Agência Brasil</a>
            </li>
            <li>
              <a href="{% url 'noticias:noticias_por_veiculo' 'Portal_G1' %}">Portal G1</a>
            </li>
            <li>
              <a href="{% url 'noticias:noticias_por_veiculo' 'Uol' %}">Uol</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>